[package]
name = "audio-streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.6"
cpal = "0.15.0"
ringbuf = "0.3.2"
hound = "3.5.0"
anyhow = "1.0.69"

